-- =============================================================================
-- CoreGuard Autonomous Vehicle SOC - Full Database Schema
-- Target Database: PostgreSQL 13+
-- Language: Korean Column Comments
-- =============================================================================

-- 1. TB_COMMON_CODE (공통 코드 테이블)
CREATE TABLE TB_COMMON_CODE (
                                GROUP_CODE VARCHAR(50) NOT NULL,
                                CODE VARCHAR(50) NOT NULL,
                                CODE_NAME VARCHAR(100) NOT NULL,
                                SORT_ORDER INT DEFAULT 1 NOT NULL,
                                IS_ACTIVE VARCHAR(1) DEFAULT 'Y' NOT NULL,
                                DESCRIPTION VARCHAR(255),
                                CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                CONSTRAINT PK_TB_COMMON_CODE PRIMARY KEY (GROUP_CODE, CODE)
);

COMMENT ON TABLE TB_COMMON_CODE IS '시스템 공통 코드 및 상태 값을 관리하는 중앙 공통 코드 테이블';
COMMENT ON COLUMN TB_COMMON_CODE.GROUP_CODE IS '코드 그룹 ID (예: INCIDENT_STATUS, VEHICLE_STATUS, METRIC_TYPE)';
COMMENT ON COLUMN TB_COMMON_CODE.CODE IS '그룹 내 상세 코드 ID (예: INC_NEW, VEH_ACTIVE)';
COMMENT ON COLUMN TB_COMMON_CODE.CODE_NAME IS '화면에 표시될 코드명 (예: "신규 인시던트")';
COMMENT ON COLUMN TB_COMMON_CODE.SORT_ORDER IS 'UI 드롭다운 및 목록 출력 시 정렬 순서';
COMMENT ON COLUMN TB_COMMON_CODE.IS_ACTIVE IS '코드 사용 여부 (Y: 사용, N: 미사용)';
COMMENT ON COLUMN TB_COMMON_CODE.DESCRIPTION IS '해당 공통 코드에 대한 상세 설명';
COMMENT ON COLUMN TB_COMMON_CODE.CREATED_AT IS '공통 코드 등록 일시';


-- 2. TB_USERS (사용자 및 관제원 테이블)
CREATE TABLE TB_USERS (
                          USER_ID VARCHAR(50) NOT NULL,
                          EMAIL VARCHAR(100) NOT NULL,
                          PASSWORD_HASH VARCHAR(255) NOT NULL,
                          USERNAME VARCHAR(100) NOT NULL,
                          ROLE_CODE VARCHAR(30) NOT NULL,
                          IS_ACTIVE VARCHAR(1) DEFAULT 'Y' NOT NULL,
                          FAILED_ATTEMPTS INT DEFAULT 0 NOT NULL,
                          LAST_LOGIN_AT TIMESTAMPTZ,
                          CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT PK_TB_USERS PRIMARY KEY (USER_ID),
                          CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE TB_USERS IS 'SOC 관제 센터 사용자 및 관제원 계정 테이블';
COMMENT ON COLUMN TB_USERS.USER_ID IS '관제원 고유 ID (예: USR-001)';
COMMENT ON COLUMN TB_USERS.EMAIL IS '로그인용 이메일 주소';
COMMENT ON COLUMN TB_USERS.PASSWORD_HASH IS 'BCrypt 암호화된 비밀번호 해시';
COMMENT ON COLUMN TB_USERS.USERNAME IS '관제원 이름 (예: Alex S.)';
COMMENT ON COLUMN TB_USERS.ROLE_CODE IS '권한 역할 코드 (예: ROLE_ADMIN, ROLE_DISPATCHER)';
COMMENT ON COLUMN TB_USERS.IS_ACTIVE IS '계정 활성화 상태 (Y: 활성, N: 잠금)';
COMMENT ON COLUMN TB_USERS.FAILED_ATTEMPTS IS '비밀번호 연속 실패 횟수';
COMMENT ON COLUMN TB_USERS.LAST_LOGIN_AT IS '최종 로그인 일시';
COMMENT ON COLUMN TB_USERS.CREATED_AT IS '계정 생성 일시';


-- 3. TB_ROLE_PERMISSIONS (역할별 권한 매핑 테이블)
CREATE TABLE TB_ROLE_PERMISSIONS (
                                     ROLE_CODE VARCHAR(30) NOT NULL,
                                     PERMISSION_CODE VARCHAR(50) NOT NULL,
                                     GRANTED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     GRANTED_BY VARCHAR(50),
                                     CONSTRAINT PK_TB_ROLE_PERMISSIONS PRIMARY KEY (ROLE_CODE, PERMISSION_CODE),
                                     CONSTRAINT FK_ROLE_PERM_USER FOREIGN KEY (GRANTED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE TB_ROLE_PERMISSIONS IS 'RBAC 역할별 동적 기능 접근 권한 매핑 테이블';
COMMENT ON COLUMN TB_ROLE_PERMISSIONS.ROLE_CODE IS '권한을 부여할 역할 코드 (예: ROLE_ADMIN)';
COMMENT ON COLUMN TB_ROLE_PERMISSIONS.PERMISSION_CODE IS '부여된 상세 권한 코드 (예: EMERGENCY_STOP, EDIT_POLICY)';
COMMENT ON COLUMN TB_ROLE_PERMISSIONS.GRANTED_AT IS '권한 부여 일시';
COMMENT ON COLUMN TB_ROLE_PERMISSIONS.GRANTED_BY IS '권한을 변경한 관리자 ID';


-- 4. TB_API_KEYS (API 키 및 연동 관리)
CREATE TABLE TB_API_KEYS (
                             KEY_ID BIGINT GENERATED ALWAYS AS IDENTITY,
                             KEY_NAME VARCHAR(100) NOT NULL,
                             API_KEY_HASH VARCHAR(255) NOT NULL,
                             KEY_TYPE VARCHAR(30) NOT NULL,
                             STATUS VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
                             CREATED_BY VARCHAR(50) NOT NULL,
                             CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             REVOKED_AT TIMESTAMPTZ,
                             CONSTRAINT PK_TB_API_KEYS PRIMARY KEY (KEY_ID),
                             CONSTRAINT FK_API_KEYS_USER FOREIGN KEY (CREATED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE CASCADE
);

COMMENT ON TABLE TB_API_KEYS IS '텔레메트리 수신 및 외부 연동용 API 인증 키 관리 테이블';
COMMENT ON COLUMN TB_API_KEYS.KEY_ID IS 'API 키 고유 번호 (자동 증가)';
COMMENT ON COLUMN TB_API_KEYS.KEY_NAME IS 'API 키 식별 이름 (예: seoul-gangnam-telemetry-ingest)';
COMMENT ON COLUMN TB_API_KEYS.API_KEY_HASH IS '인증 검증용 API 키 해시값';
COMMENT ON COLUMN TB_API_KEYS.KEY_TYPE IS '키 용도 구분 (INGRESS: 수신, EGRESS: 송신)';
COMMENT ON COLUMN TB_API_KEYS.STATUS IS '키 상태 (ACTIVE: 사용중, REVOKED: 폐기, EXPIRED: 만료)';
COMMENT ON COLUMN TB_API_KEYS.CREATED_BY IS '키 발급 관제원 ID';
COMMENT ON COLUMN TB_API_KEYS.CREATED_AT IS '키 발급 일시';
COMMENT ON COLUMN TB_API_KEYS.REVOKED_AT IS '키 폐기 일시';


-- 5. TB_VEHICLES (자율주행 차량 대장)
CREATE TABLE TB_VEHICLES (
                             VEHICLE_ID VARCHAR(50) NOT NULL,
                             VIN VARCHAR(17) NOT NULL,
                             MODEL VARCHAR(50) NOT NULL,
                             STATUS VARCHAR(30) NOT NULL,
                             SPEED_LIMIT DOUBLE PRECISION DEFAULT 60.0 NOT NULL,
                             ASSIGNED_ZONE VARCHAR(100),
                             FIRMWARE_VERSION VARCHAR(30),
                             LATITUDE DOUBLE PRECISION,
                             LONGITUDE DOUBLE PRECISION,
                             LAST_PING_AT TIMESTAMPTZ,
                             CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             CONSTRAINT PK_TB_VEHICLES PRIMARY KEY (VEHICLE_ID),
                             CONSTRAINT UQ_VEHICLES_VIN UNIQUE (VIN)
);

COMMENT ON TABLE TB_VEHICLES IS '관제 대상 자율주행 차량 정보 대장';
COMMENT ON COLUMN TB_VEHICLES.VEHICLE_ID IS '차량 식별 ID (예: ROBOTAXI-01)';
COMMENT ON COLUMN TB_VEHICLES.VIN IS '차대번호 (17자리 고유번호)';
COMMENT ON COLUMN TB_VEHICLES.MODEL IS '차량 모델명 (예: Hyundai IONIQ 5 Robotaxi)';
COMMENT ON COLUMN TB_VEHICLES.STATUS IS '차량 상태 (VEH_ACTIVE, VEH_MAINTENANCE, VEH_EMERGENCY_STOP)';
COMMENT ON COLUMN TB_VEHICLES.SPEED_LIMIT IS '소프트웨어 설정 최고 제한 속도 (km/h)';
COMMENT ON COLUMN TB_VEHICLES.ASSIGNED_ZONE IS '할당된 운행 구역명 (예: Gangnam District)';
COMMENT ON COLUMN TB_VEHICLES.FIRMWARE_VERSION IS '자율주행 시스템 펌웨어 버전';
COMMENT ON COLUMN TB_VEHICLES.LATITUDE IS '최근 수신된 GPS 위도';
COMMENT ON COLUMN TB_VEHICLES.LONGITUDE IS '최근 수신된 GPS 경도';
COMMENT ON COLUMN TB_VEHICLES.LAST_PING_AT IS '최종 통신 신호 수신 일시';
COMMENT ON COLUMN TB_VEHICLES.CREATED_AT IS '차량 시스템 등록 일시';


ALTER TABLE TB_VEHICLES
    ADD COLUMN IF NOT EXISTS BATTERY INT DEFAULT 100;
COMMENT ON COLUMN TB_VEHICLES.BATTERY IS '최근 배터리 잔량 (%)';

ADD COLUMN VEHICLE_TYPE VARCHAR(30);

COMMENT ON COLUMN TB_VEHICLES.VEHICLE_TYPE IS '차량 유형 (ROBOTAXI, SHUTTLE, DELIVERY 등)';

-- 6. TB_DEVICES (차량 탑재 장비 및 센서)
CREATE TABLE TB_DEVICES (
                            DEVICE_ID VARCHAR(50) NOT NULL,
                            VEHICLE_ID VARCHAR(50) NOT NULL,
                            DEVICE_TYPE VARCHAR(30) NOT NULL,
                            SERIAL_NUMBER VARCHAR(50) NOT NULL,
                            STATUS VARCHAR(30) NOT NULL,
                            FIRMWARE_VERSION VARCHAR(30),
                            LAST_DIAGNOSTIC_AT TIMESTAMPTZ,
                            CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            CONSTRAINT PK_TB_DEVICES PRIMARY KEY (DEVICE_ID),
                            CONSTRAINT FK_DEVICES_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES TB_VEHICLES(VEHICLE_ID) ON DELETE CASCADE
);

COMMENT ON TABLE TB_DEVICES IS '차량에 장착된 센서 및 통신 모듈 정보 (LiDAR, V2X, Camera 등)';
COMMENT ON COLUMN TB_DEVICES.DEVICE_ID IS '장비 고유 ID (예: DEV-LIDAR-01)';
COMMENT ON COLUMN TB_DEVICES.VEHICLE_ID IS '장비가 장착된 차량 ID';
COMMENT ON COLUMN TB_DEVICES.DEVICE_TYPE IS '장비 유형 (DEV_LIDAR, DEV_V2X, DEV_CAMERA, DEV_RADAR)';
COMMENT ON COLUMN TB_DEVICES.SERIAL_NUMBER IS '제조사 시리얼 번호';
COMMENT ON COLUMN TB_DEVICES.STATUS IS '장비 진단 상태 (DEV_ONLINE, DEV_DEGRADED, DEV_OFFLINE)';
COMMENT ON COLUMN TB_DEVICES.FIRMWARE_VERSION IS '해당 센서 펌웨어 버전';
COMMENT ON COLUMN TB_DEVICES.LAST_DIAGNOSTIC_AT IS '최근 자체 진단 수행 일시';
COMMENT ON COLUMN TB_DEVICES.CREATED_AT IS '장비 등록 및 차량 매핑 일시';

-- 행정구역 경계 정보 테이블 (KakaoMap 연동 및 구역 선택용)
CREATE TABLE TB_ADMIN_REGIONS (
    -- 행정구역 코드 (예: '1117000000' - 용산구)
    REGION_CODE VARCHAR(10) PRIMARY KEY,
    -- 행정구역 계층 정보
    CITY_NAME VARCHAR(50) NOT NULL,          -- 특별/광역시 및 도 (예: '서울특별시', '경기도')
    DISTRICT_NAME VARCHAR(50) NOT NULL,      -- 시/군/구 (예: '용산구', '강남구')
    SUB_DISTRICT_NAME VARCHAR(50) NULL,      -- 읍/면/동 (예: '이태원1동', '한남동')
    -- KakaoMap 연동용 GeoJSON 경계 좌표 데이터 (Polygon 또는 MultiPolygon)
    BOUNDARY_POLYGON JSONB NOT NULL,
    -- 상태 및 감사 정보
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,  -- 활성화 여부
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW() -- 등록 일시
);

-- 테이블 및 컬럼 주석 추가 (PostgreSQL Comment)
COMMENT ON TABLE TB_ADMIN_REGIONS IS '행정구역 경계 좌표(GeoJSON) 마스터 테이블';
COMMENT ON COLUMN TB_ADMIN_REGIONS.REGION_CODE IS '행정구역 코드 (Primary Key)';
COMMENT ON COLUMN TB_ADMIN_REGIONS.CITY_NAME IS '시/도 명칭';
COMMENT ON COLUMN TB_ADMIN_REGIONS.DISTRICT_NAME IS '시/군/구 명칭';
COMMENT ON COLUMN TB_ADMIN_REGIONS.SUB_DISTRICT_NAME IS '읍/면/동 명칭 (선택 사항)';
COMMENT ON COLUMN TB_ADMIN_REGIONS.BOUNDARY_POLYGON IS 'KakaoMap 렌더링용 GeoJSON 영역 좌표 데이터';
COMMENT ON COLUMN TB_ADMIN_REGIONS.IS_ACTIVE IS '사용 여부 (TRUE: 사용, FALSE: 미사용)';
COMMENT ON COLUMN TB_ADMIN_REGIONS.CREATED_AT IS '데이터 생성 일시';

-- 드롭다운 Select 조회를 위한 빠른 검색 인덱스
CREATE INDEX IF NOT EXISTS IDX_ADMIN_REGIONS_LOOKUP 
ON TB_ADMIN_REGIONS (CITY_NAME, DISTRICT_NAME);


-- 7. TB_SECURITY_POLICIES (보안 정책 및 지오펜스)
CREATE TABLE TB_SECURITY_POLICIES (
                                      POLICY_ID VARCHAR(50) NOT NULL,
                                      POLICY_NAME VARCHAR(100) NOT NULL,
                                      DESCRIPTION VARCHAR(255),
                                      GEOFENCE_POLYGON JSONB,
                                      VIOLATION_ACTION_CODE VARCHAR(50) NOT NULL,
                                      IS_ACTIVE VARCHAR(1) DEFAULT 'Y' NOT NULL,
                                      CREATED_BY VARCHAR(50),
                                      CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                      UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                      CONSTRAINT PK_TB_SECURITY_POLICIES PRIMARY KEY (POLICY_ID),
                                      CONSTRAINT FK_POLICIES_USER FOREIGN KEY (CREATED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE TB_SECURITY_POLICIES IS '보안 프로필, 지오펜스 영역 및 위반 시 조치 규칙 테이블';
COMMENT ON COLUMN TB_SECURITY_POLICIES.POLICY_ID IS '보안 정책 ID (예: POL_HIGHWAY_ROBOTAXI)';
COMMENT ON COLUMN TB_SECURITY_POLICIES.POLICY_NAME IS '정책 이름 (예: "고속도로 로보택시 안전 규칙")';
COMMENT ON COLUMN TB_SECURITY_POLICIES.DESCRIPTION IS '정책 세부 설명';
COMMENT ON COLUMN TB_SECURITY_POLICIES.GEOFENCE_POLYGON IS '운행 허용 지오펜스 다각형 GPS 좌표 (JSONB 배열)';
COMMENT ON COLUMN TB_SECURITY_POLICIES.VIOLATION_ACTION_CODE IS '위반 시 자동 제어 동작 (ACT_WARN, ACT_RAISE_INCIDENT, ACT_FORCE_STOP)';
COMMENT ON COLUMN TB_SECURITY_POLICIES.IS_ACTIVE IS '정책 적용 여부 (Y: 사용, N: 비활성)';
COMMENT ON COLUMN TB_SECURITY_POLICIES.CREATED_BY IS '정책 작성 관제원 ID';
COMMENT ON COLUMN TB_SECURITY_POLICIES.CREATED_AT IS '정책 생성 일시';
COMMENT ON COLUMN TB_SECURITY_POLICIES.UPDATED_AT IS '정책 최종 수정 일시';

ALTER TABLE TB_SECURITY_POLICIES 
    ADD COLUMN IF NOT EXISTS PRIORITY INT NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS START_TIME TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS END_TIME TIMESTAMPTZ NULL;
 


-- 8. TB_VEHICLE_POLICIES (차량별 정책 매핑)
CREATE TABLE TB_VEHICLE_POLICIES (
                                     VEHICLE_ID VARCHAR(50) NOT NULL,
                                     POLICY_ID VARCHAR(50) NOT NULL,
                                     ASSIGNED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     ASSIGNED_BY VARCHAR(50),
                                     CONSTRAINT PK_TB_VEHICLE_POLICIES PRIMARY KEY (VEHICLE_ID, POLICY_ID),
                                     CONSTRAINT FK_VP_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES TB_VEHICLES(VEHICLE_ID) ON DELETE CASCADE,
                                     CONSTRAINT FK_VP_POLICY FOREIGN KEY (POLICY_ID) REFERENCES TB_SECURITY_POLICIES(POLICY_ID) ON DELETE CASCADE,
                                     CONSTRAINT FK_VP_USER FOREIGN KEY (ASSIGNED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE TB_VEHICLE_POLICIES IS '차량과 적용된 보안 정책 간의 다대다(N:M) 매핑 테이블';
COMMENT ON COLUMN TB_VEHICLE_POLICIES.VEHICLE_ID IS '정책을 적용할 차량 ID';
COMMENT ON COLUMN TB_VEHICLE_POLICIES.POLICY_ID IS '적용할 보안 정책 ID';
COMMENT ON COLUMN TB_VEHICLE_POLICIES.ASSIGNED_AT IS '정책 할당 일시';
COMMENT ON COLUMN TB_VEHICLE_POLICIES.ASSIGNED_BY IS '정책을 할당한 관제원 ID';


-- 9. TB_THRESHOLD_CONFIGS (임계값 슬라이더 설정)
CREATE TABLE TB_THRESHOLD_CONFIGS (
                                      CONFIG_ID BIGINT GENERATED ALWAYS AS IDENTITY,
                                      POLICY_ID VARCHAR(50) DEFAULT '' NULL,
                                      METRIC_TYPE VARCHAR(50) NOT NULL,
                                      WARN_VALUE DOUBLE PRECISION NOT NULL,
                                      CRIT_VALUE DOUBLE PRECISION NOT NULL,
                                      OPERATOR VARCHAR(10) NOT NULL,
                                      UNIT VARCHAR(20),
                                      CONSTRAINT PK_TB_THRESHOLD_CONFIGS PRIMARY KEY (CONFIG_ID),
                                      CONSTRAINT UQ_POLICY_METRIC UNIQUE (POLICY_ID, METRIC_TYPE),
                                      CONSTRAINT FK_THRESHOLDS_USER FOREIGN KEY (UPDATED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE TB_THRESHOLD_CONFIGS IS 'UI 슬라이더 기반 지표별 경고/위험 임계값 설정 테이블';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.CONFIG_ID IS '임계값 설정 고유 ID';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.POLICY_ID IS '연관된 보안 정책 ID (또는 GLOBAL_DEFAULT)';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.METRIC_TYPE IS '모니터링 지표 유형 (METRIC_BATTERY_SOC, METRIC_V2X_LATENCY, METRIC_LIDAR_PPS)';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.WARN_VALUE IS 'Warning 경고 수준 임계값';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.CRIT_VALUE IS 'Critical 위험 수준 임계값';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.OPERATOR IS '임계값 비교 연산자 (< 또는 >)';
COMMENT ON COLUMN TB_THRESHOLD_CONFIGS.UNIT IS '지표 측정 단위 (%, ms, pps 등)';


ALTER TABLE TB_THRESHOLD_CONFIGS 
    ADD COLUMN IF NOT EXISTS VEHICLE_TYPE VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS IS_GLOBAL_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS CREATED_BY VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS IS_ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    ADD COLUMN IF NOT EXISTS DEACTIVATED_AT TIMESTAMPTZ NULL;


-- 10. TB_INCIDENTS (인시던트 및 이상 징후)
CREATE TABLE TB_INCIDENTS (
                              INCIDENT_ID VARCHAR(50) NOT NULL,
                              VEHICLE_ID VARCHAR(50) NOT NULL,
                              DEVICE_ID VARCHAR(50),
                              POLICY_ID VARCHAR(50),
                              SEVERITY VARCHAR(20) NOT NULL,
                              INCIDENT_TYPE VARCHAR(50) NOT NULL,
                              STATUS VARCHAR(30) DEFAULT 'INC_NEW' NOT NULL,
                              TITLE VARCHAR(200) NOT NULL,
                              DESCRIPTION TEXT,
                              TRIGGER_VALUE DOUBLE PRECISION,
                              THRESHOLD_VALUE DOUBLE PRECISION,
                              LATITUDE DOUBLE PRECISION,
                              LONGITUDE DOUBLE PRECISION,
                              ACKNOWLEDGED_BY VARCHAR(50),
                              ACKNOWLEDGED_AT TIMESTAMPTZ,
                              RESOLVED_AT TIMESTAMPTZ,
                              CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT PK_TB_INCIDENTS PRIMARY KEY (INCIDENT_ID),
                              CONSTRAINT FK_INCIDENTS_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES TB_VEHICLES(VEHICLE_ID) ON DELETE CASCADE,
                              CONSTRAINT FK_INCIDENTS_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TB_DEVICES(DEVICE_ID) ON DELETE SET NULL,
                              CONSTRAINT FK_INCIDENTS_POLICY FOREIGN KEY (POLICY_ID) REFERENCES TB_SECURITY_POLICIES(POLICY_ID) ON DELETE SET NULL,
                              CONSTRAINT FK_INCIDENTS_ACK_USER FOREIGN KEY (ACKNOWLEDGED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE TB_INCIDENTS IS '감지된 이상 징후, 보안 위반 및 인시던트 대장';
COMMENT ON COLUMN TB_INCIDENTS.INCIDENT_ID IS '인시던트 고유 번호 (예: INC-20260902-001)';
COMMENT ON COLUMN TB_INCIDENTS.VEHICLE_ID IS '이상이 발생한 차량 ID';
COMMENT ON COLUMN TB_INCIDENTS.DEVICE_ID IS '원인이 된 센서/장비 ID (선택사항)';
COMMENT ON COLUMN TB_INCIDENTS.POLICY_ID IS '위반된 보안 정책 ID (선택사항)';
COMMENT ON COLUMN TB_INCIDENTS.SEVERITY IS '심각도 수준 (WARNING, CRITICAL)';
COMMENT ON COLUMN TB_INCIDENTS.INCIDENT_TYPE IS '인시던트 유형 (INC_V2X_LATENCY_HIGH, INC_GEOFENCE_VIOLATION 등)';
COMMENT ON COLUMN TB_INCIDENTS.STATUS IS '조치 상태 (INC_NEW: 신규, INC_ACK: 접수, INC_RESOLVED: 해결)';
COMMENT ON COLUMN TB_INCIDENTS.TITLE IS '대시보드 표시용 인시던트 제목';
COMMENT ON COLUMN TB_INCIDENTS.DESCRIPTION IS '이상 발생 원인 및 상세 내용';
COMMENT ON COLUMN TB_INCIDENTS.TRIGGER_VALUE IS '인시던트를 유발한 실제 감지 측정값';
COMMENT ON COLUMN TB_INCIDENTS.THRESHOLD_VALUE IS '위반된 설정 임계값';
COMMENT ON COLUMN TB_INCIDENTS.LATITUDE IS '발생 당시 차량 GPS 위도';
COMMENT ON COLUMN TB_INCIDENTS.LONGITUDE IS '발생 당시 차량 GPS 경도';
COMMENT ON COLUMN TB_INCIDENTS.ACKNOWLEDGED_BY IS '인시던트를 접수(ACK)한 관제원 ID';
COMMENT ON COLUMN TB_INCIDENTS.ACKNOWLEDGED_AT IS '관제원 접수 일시';
COMMENT ON COLUMN TB_INCIDENTS.RESOLVED_AT IS '인시던트 조치 완료/종결 일시';
COMMENT ON COLUMN TB_INCIDENTS.CREATED_AT IS '인시던트 감지 및 생성 일시';


-- 11. TB_INCIDENT_NOTES (인시던트 조사 로그)
CREATE TABLE TB_INCIDENT_NOTES (
                                   NOTE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
                                   INCIDENT_ID VARCHAR(50) NOT NULL,
                                   OPERATOR_ID VARCHAR(50) NOT NULL,
                                   NOTE_TEXT TEXT NOT NULL,
                                   CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   CONSTRAINT PK_TB_INCIDENT_NOTES PRIMARY KEY (NOTE_ID),
                                   CONSTRAINT FK_NOTES_INCIDENT FOREIGN KEY (INCIDENT_ID) REFERENCES TB_INCIDENTS(INCIDENT_ID) ON DELETE CASCADE,
                                   CONSTRAINT FK_NOTES_OPERATOR FOREIGN KEY (OPERATOR_ID) REFERENCES TB_USERS(USER_ID) ON DELETE CASCADE
);

COMMENT ON TABLE TB_INCIDENT_NOTES IS '관제원의 인시던트 조사 이력 및 조치 소평 작성 로그';
COMMENT ON COLUMN TB_INCIDENT_NOTES.NOTE_ID IS '조사 노트 고유 번호';
COMMENT ON COLUMN TB_INCIDENT_NOTES.INCIDENT_ID IS '연관된 인시던트 ID';
COMMENT ON COLUMN TB_INCIDENT_NOTES.OPERATOR_ID IS '노트를 작성한 관제원 ID';
COMMENT ON COLUMN TB_INCIDENT_NOTES.NOTE_TEXT IS '조사 내용 및 조치 사항 메모';
COMMENT ON COLUMN TB_INCIDENT_NOTES.CREATED_AT IS '메모 작성 일시';


-- 12. TB_TELEMETRY_LOGS (실시간 텔레메트리 시계열 로그)
CREATE TABLE TB_TELEMETRY_LOGS (
                                   TELEMETRY_ID BIGINT GENERATED ALWAYS AS IDENTITY,
                                   VEHICLE_ID VARCHAR(50) NOT NULL,
                                   DEVICE_ID VARCHAR(50),
                                   METRIC_TYPE VARCHAR(50) NOT NULL,
                                   METRIC_VALUE DOUBLE PRECISION NOT NULL,
                                   UNIT VARCHAR(30),
                                   RECORDED_AT TIMESTAMPTZ NOT NULL,
                                   RECEIVED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   CONSTRAINT PK_TB_TELEMETRY_LOGS PRIMARY KEY (TELEMETRY_ID),
                                   CONSTRAINT FK_TELEMETRY_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES TB_VEHICLES(VEHICLE_ID) ON DELETE CASCADE
);

COMMENT ON TABLE TB_TELEMETRY_LOGS IS '차량 수집 데이터 실시간 시계열 스트림 로그 (Time-Series)';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.TELEMETRY_ID IS '텔레메트리 패킷 ID';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.VEHICLE_ID IS '데이터를 전송한 차량 ID';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.DEVICE_ID IS '데이터를 측정한 센서/장비 ID';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.METRIC_TYPE IS '측정 지표 유형 (METRIC_BATTERY_SOC, METRIC_V2X_LATENCY 등)';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.METRIC_VALUE IS '수집된 수치 데이터';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.UNIT IS '측정 단위 (%, ms, pps)';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.RECORDED_AT IS '차량 단말기 측정 시각';
COMMENT ON COLUMN TB_TELEMETRY_LOGS.RECEIVED_AT IS '서버 수신 및 DB 저장 시각';


-- 13. TB_AUDIT_LOGS (블록체인형 감사 로그)
CREATE TABLE TB_AUDIT_LOGS (
                               LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY,
                               USER_ID VARCHAR(50) NOT NULL,
                               ACTION_NAME VARCHAR(100) NOT NULL,
                               TARGET_ENTITY VARCHAR(50) NOT NULL,
                               DETAILS JSONB,
                               PREVIOUS_HASH VARCHAR(64),
                               CRYPTO_HASH VARCHAR(64) NOT NULL,
                               PERFORMED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               CONSTRAINT PK_TB_AUDIT_LOGS PRIMARY KEY (LOG_ID),
                               CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID) ON DELETE CASCADE
);

COMMENT ON TABLE TB_AUDIT_LOGS IS 'SHA-256 해시 체인 기반 관제원 행위 위변조 방지 감사 로그';
COMMENT ON COLUMN TB_AUDIT_LOGS.LOG_ID IS '감사 로그 고유 번호';
COMMENT ON COLUMN TB_AUDIT_LOGS.USER_ID IS '작업을 수행한 관제원 ID';
COMMENT ON COLUMN TB_AUDIT_LOGS.ACTION_NAME IS '수행한 작업명 (예: UPDATE_THRESHOLDS, EMERGENCY_STOP)';
COMMENT ON COLUMN TB_AUDIT_LOGS.TARGET_ENTITY IS '작업 대상 테이블/엔티티 (예: TB_THRESHOLD_CONFIGS)';
COMMENT ON COLUMN TB_AUDIT_LOGS.DETAILS IS '변경 전/후 데이터를 포함한 상세 JSONB 객체';
COMMENT ON COLUMN TB_AUDIT_LOGS.PREVIOUS_HASH IS '이전 로그의 SHA-256 해시값 (체인 연결용)';
COMMENT ON COLUMN TB_AUDIT_LOGS.CRYPTO_HASH IS '현재 로그 행 전체의 SHA-256 검증 해시값';
COMMENT ON COLUMN TB_AUDIT_LOGS.PERFORMED_AT IS '작업 수행 일시';


ALTER TABLE tb_audit_logs 
    ADD COLUMN level VARCHAR(20) NOT NULL DEFAULT 'INFO',
    ADD COLUMN source VARCHAR(100);
-- Комментарии к колонкам (для документации в БД)
COMMENT ON COLUMN tb_audit_logs.level IS '로그 등급 (SECURITY, ERROR, WARN, INFO)';
COMMENT ON COLUMN tb_audit_logs.source IS '발생 소스/IP/노드 (예: 10.42.9.11, AV-Ingress-12)';

INSERT INTO TB_USERS (USER_ID, EMAIL, PASSWORD_HASH, USERNAME, ROLE_CODE)
VALUES ('USR-001', 'admin@coreguard.com', 'hashed_pass', 'Alex Admin', 'ROLE_ADMIN');


-- 14. TB_OPA_POLICIES ( ABAC)

CREATE TABLE TB_OPA_POLICIES (
    POLICY_ID VARCHAR(50) PRIMARY KEY,           -- e.g., 'POL-01'
    POLICY_NAME VARCHAR(100) NOT NULL,           -- e.g., 'Emergency Braking Overrides'
    PACKAGE_NAME VARCHAR(100) NOT NULL,          -- e.g., 'soc.authz.fleet'
    REGO_CODE TEXT NOT NULL,                     -- Текст Rego-скрипта
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,     -- Статус (ACTIVE/INACTIVE)
    
    -- Системный аудит
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_BY VARCHAR(50) NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_OPA_POLICIES_USER FOREIGN KEY (CREATED_BY) REFERENCES TB_USERS(USER_ID)
);

COMMENT ON TABLE TB_OPA_POLICIES IS 'OPA Rego 기반 ABAC 보안 정책 관리 테이블';
COMMENT ON COLUMN TB_OPA_POLICIES.POLICY_ID IS '정책 고유 식별자 (예: POL-01)';
COMMENT ON COLUMN TB_OPA_POLICIES.REGO_CODE IS 'Open Policy Agent 실행용 Rego 코드';


--15 . API Gateway 라우팅 및 미들웨어 설정 테이블
CREATE TABLE TB_GATEWAY_ROUTES (
    ROUTE_ID VARCHAR(50) PRIMARY KEY,
    PATH VARCHAR(255) NOT NULL,
    HTTP_METHOD VARCHAR(10) NOT NULL,
    UPSTREAM_URL VARCHAR(255) NOT NULL,
    AUTH_TYPE VARCHAR(30) NOT NULL,
    RATE_LIMIT_RPM INT NOT NULL DEFAULT 6000,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    MIDDLEWARE_CHAIN JSONB NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE TB_GATEWAY_ROUTES IS 'API 게이트웨이 라우팅 및 미들웨어 정책 관리 테이블';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.ROUTE_ID IS '라우트 고유 식별자 (예: route-telemetry-ingest)';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.PATH IS '요청 엔드포인트 URI 경로 (예: /v1/telemetry/ingest)';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.HTTP_METHOD IS 'HTTP 메서드 (POST, GET, gRPC 등)';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.UPSTREAM_URL IS '내부 포워딩 대상 쿠버네티스 서비스 주소';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.AUTH_TYPE IS '인증 방식 (mTLS, OIDC_JWT, API_KEY 등)';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.RATE_LIMIT_RPM IS '분당 최대 허용 요청 수 (RPM)';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.STATUS IS '라우트 상태 (ACTIVE, DEGRADED, MAINTENANCE)';
COMMENT ON COLUMN TB_GATEWAY_ROUTES.MIDDLEWARE_CHAIN IS '체이닝된 미들웨어 필터 목록 (JSONB)';


-- 16. OAuth 2.0 & OIDC 클라이언트 등록 테이블
CREATE TABLE TB_OAUTH_CLIENTS (
    CLIENT_ID VARCHAR(100) PRIMARY KEY,
    CLIENT_NAME VARCHAR(150) NOT NULL,
    CLIENT_SECRET_HASH VARCHAR(255) NULL,
    ALLOWED_GRANT_TYPES TEXT[] NOT NULL,
    AUTH_FLOW VARCHAR(100) NOT NULL,
    ASSIGNED_SCOPES TEXT[] NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE TB_OAUTH_CLIENTS IS 'OAuth 2.0 및 OIDC 등록 클라이언트 애플리케이션 관리 테이블';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.CLIENT_ID IS '클라이언트 앱 고유 식별자';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.CLIENT_NAME IS '클라이언트 애플리케이션 명칭';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.CLIENT_SECRET_HASH IS '클라이언트 시크릿 해시값 (PKCE 사용 시 NULL 허용)';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.ALLOWED_GRANT_TYPES IS '허용된 OAuth Grant Type 배열';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.AUTH_FLOW IS '인증 메커니즘 흐름 (예: PKCE + OIDC, mTLS + Token Exchange)';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.ASSIGNED_SCOPES IS '부여된 접근 권한 범위(Scope) 배열';
COMMENT ON COLUMN TB_OAUTH_CLIENTS.STATUS IS '클라이언트 활성화 상태 (ACTIVE, INACTIVE, SUSPENDED)';


    -- 17. 자율주행 차량 mTLS X.509 기기 인증서 관리 테이블
    CREATE TABLE TB_DEVICE_CERTIFICATES (
        CERT_ID VARCHAR(50) PRIMARY KEY,
        VEHICLE_ID VARCHAR(50) NOT NULL,
        SUBJECT_DN VARCHAR(255) NOT NULL,
        FINGERPRINT_SHA256 VARCHAR(64) UNIQUE NOT NULL,
        ISSUER_NAME VARCHAR(100) NOT NULL,
        STATUS VARCHAR(20) NOT NULL DEFAULT 'VALID',
        VALID_FROM TIMESTAMPTZ NOT NULL,
        VALID_UNTIL TIMESTAMPTZ NOT NULL,
        REVOKED_AT TIMESTAMPTZ NULL,
        REVOCATION_REASON VARCHAR(255) NULL,
        CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT FK_DEVICE_CERT_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES TB_VEHICLES(VEHICLE_ID)
    );

    COMMENT ON TABLE TB_DEVICE_CERTIFICATES IS '자율주행 차량 mTLS X.509 기기 인증서 관리 테이블';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.CERT_ID IS '인증서 고유 식별자';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.VEHICLE_ID IS '연동된 차량 고유 식별자 (FK)';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.SUBJECT_DN IS '인증서 주체 식별명 (Subject Distinguished Name)';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.FINGERPRINT_SHA256 IS '인증서 SHA-256 지문 (Fingerprint)';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.ISSUER_NAME IS '발급 인증 기관(CA) 명칭';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.STATUS IS '인증서 상태 (VALID, EXPIRING_SOON, REVOKED)';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.VALID_FROM IS '인증서 유효 시작 일시';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.VALID_UNTIL IS '인증서 만료 예정 일시';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.REVOKED_AT IS '인증서 폐기 처리 일시';
    COMMENT ON COLUMN TB_DEVICE_CERTIFICATES.REVOCATION_REASON IS '인증서 폐기 사유';