version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: coreguard-postgres
    environment:
      POSTGRES_DB: coreguard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user01 # Поменяй на свой пароль
    ports:
      - "5432:5432"
    volumes:
      # Сохраняет данные БД на диске, чтобы они не стирались при перезапуске
      - postgres_data:/var/lib/postgresql/data
      # Автоматически выполняет наш DDL скрипт при первом создании контейнера
      - ./coreguard_ddl_13_tables.sql:/docker-entrypoint-initdb.d/coreguard_ddl_13_tables.sql

volumes:
  postgres_data: