server:
  port: 8090

spring:
  application:
    name: coreguard-soc-backend

  datasource:
    url: jdbc:postgresql://112.168.140.248:5432/coreguard_db
    username: postgres
    password: user01
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Проверяет соответствие Entity-классов существующим таблицам, НЕ меняя схему
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  # Base64 encoded or 256-bit secret key
  secret: c29tZS12ZXJ5LXNlY3VyZS1hbmQtbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtY29yZWd1YXJkLXNvYy0yNTY=
  access-expiration: 900000 # 15 minutes (in milliseconds)
  refresh-expiration: 10800000 # 3 hours (in milliseconds)